/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PerfCallback */

#ifndef _Included_PerfCallback
#define _Included_PerfCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PerfCallback
 * Method:    preparePerfEvent
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_PerfCallback_startPerfEvent
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     PerfCallback
 * Method:    stopPerfEvent
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_PerfCallback_stopPerfEvent
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
